name: debug-workflow

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt

      - name: Run tests
        run: |
          echo "==== DEBUG START ===="
          ls -R
          echo "==== DEBUG END ===="
          which python
          python --version
          python -m pip list
          PYTHONPATH=. python -m pytest -v ./tests
