name: debug-workflow

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show files
        run: |
          echo "==== ls -R output ===="
          ls -R
          echo "==== END ===="
